// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlXrjaQ25wdZiSnRl4hVBuPjzPjlQPew',
    appId: '1:356789513515:web:6ac4bc4355a766d13c696e',
    messagingSenderId: '356789513515',
    projectId: 'flutterapp-60eb7',
    authDomain: 'flutterapp-60eb7.firebaseapp.com',
    storageBucket: 'flutterapp-60eb7.appspot.com',
    measurementId: 'G-4KS0BPYEKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfd2GNgpiVAO4hIIUjL0h2dWLydzHZf-E',
    appId: '1:356789513515:android:5da03bab7458d3453c696e',
    messagingSenderId: '356789513515',
    projectId: 'flutterapp-60eb7',
    storageBucket: 'flutterapp-60eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYzwI1z8ZTwWPfOSeZVkmZm09C-uQQ-18',
    appId: '1:356789513515:ios:2531c5ec0ec6fd0b3c696e',
    messagingSenderId: '356789513515',
    projectId: 'flutterapp-60eb7',
    storageBucket: 'flutterapp-60eb7.appspot.com',
    iosBundleId: 'com.care.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYzwI1z8ZTwWPfOSeZVkmZm09C-uQQ-18',
    appId: '1:356789513515:ios:fcd201ccecafebd03c696e',
    messagingSenderId: '356789513515',
    projectId: 'flutterapp-60eb7',
    storageBucket: 'flutterapp-60eb7.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
